/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.JPanelGradient;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luix_
 */
public class generarClave extends javax.swing.JDialog {

    private static Font fuenteSans16P = new Font("Open Sans", Font.PLAIN,16);
    private static Font fuenteSans12P = new Font("Open Sans", Font.PLAIN,12);
    private static String nombreP;
    Connection con;
    String claveGenerada="-1";
    private static Color azulF = new Color(25, 30, 111);
    private static Color gris = new Color(200, 200, 200);
    
    /**
     * Creates new form correctAddProduct
     */
    public generarClave(java.awt.Frame parent, boolean modal, String nombre, Connection cone) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        nombreP=nombre;
        con=cone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel = new JPanelGradient(Color.WHITE,new Color(25, 30, 111,53));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Panel.setOpaque(false);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(fuenteSans16P);
        jLabel3.setForeground(new java.awt.Color(43, 43, 43));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No se a escrito una clave");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 520, 20));

        jLabel4.setText("Se procedera a generar una clave");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ej. TO-12345678ROG");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 70, 200, -1));

        jLabel6.setText("Primeras dos letras:");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, 20));

        jLabel7.setText("Nombre del producto");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel8.setText("Ocho digitos generados al azar");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel9.setText("Tres ultimas letras:");
        Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel10.setText("ROG o palabra a usar");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, 100));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Por defecto: ROG");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        Panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Personalizado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        Panel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTextField1.setEnabled(false);
        Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 30));

        jButton1.setBackground(new java.awt.Color(25, 30, 111));
        jButton1.setFont(fuenteSans12P);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, 40));

        jButton2.setBackground(new java.awt.Color(25, 30, 111));
        jButton2.setFont(fuenteSans12P);
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceptar");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 40));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 30, 510, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        claveGenerada="-1";
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random r = new Random();
        boolean existe=false;
        String clave;
        if(jTextField1.getText().length()!=0){
            do{
                String numero = r.nextInt(100000000)+"";
                while(numero.length()!=8){
                    numero="0"+numero;
                }
                clave = nombreP.substring(0,3)+"-"+numero;
                if(jRadioButton1.isSelected()){
                    clave = clave+"ROG";
                }
                else{
                    clave = clave+jTextField1.getText().substring(0,3);
                }
                Statement stmt;
                try {
                    stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT count(*) from productos where idProductos=upper('"+clave+"')");
                    rs.next();
                    if(rs.getInt("count(*)")==0){
                        existe=false;
                    }
                    else{
                        existe=true;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(generarClave.class.getName()).log(Level.SEVERE, null, ex);
                }
            }while(existe==true);
            this.setClaveGenerada(clave.toUpperCase());
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()){
            jTextField1.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            jTextField1.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    public String getClaveGenerada() {
        return claveGenerada;
    }

    public void setClaveGenerada(String claveGenerada) {
        this.claveGenerada = claveGenerada;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
