/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.GhostText;
import Clases.JPanelGradient;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luix_
 */
public class salidasProducto extends javax.swing.JDialog {

    private static Font fuenteSans16P = new Font("Open Sans", Font.PLAIN,16);
    private static Font fuenteSans12P = new Font("Open Sans", Font.PLAIN,12);
    private static Font fuenteSans12B = new Font("Open Sans", Font.BOLD,12);
    private static Color gris = new Color(120,120,120);
    private static Color azulF = new Color(25,30,111);
    private static String claveProducto;
    private static String usuario;
    Connection con;
    int cantidadS;
    int cantidadD;
    float precioP;
    boolean salida = false;
    
    /**
     * Creates new form correctAddProduct
     */
    public salidasProducto(java.awt.Frame parent, boolean modal, String clave, Connection cone, String user, float precio, int cantidadDisp) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        claveProducto=clave;
        con=cone;
        usuario=user;
        precioP=precio;
        cantidadD=cantidadDisp;
        GhostText ghostText = new GhostText(detalles, "Opcional: Detalles de la salida del producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new JPanelGradient(Color.WHITE,new Color(25, 30, 111,53));
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        noNotaTF = new javax.swing.JTextField();
        receptorTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        detalles = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 30, 111)));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(fuenteSans16P);
        jLabel3.setForeground(new java.awt.Color(43, 43, 43));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad a restar");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 450, 20));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 30, 440, -1));

        cantidad.setFont(fuenteSans12P);
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setText("0");
        cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidadMouseClicked(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        Panel.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 40));

        jLabel2.setFont(fuenteSans12B);
        jLabel2.setForeground(new java.awt.Color(25, 30, 111));
        jLabel2.setText("*Numero de nota:");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        noNotaTF.setFont(fuenteSans12P);
        noNotaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noNotaTFKeyReleased(evt);
            }
        });
        Panel.add(noNotaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 420, 30));

        receptorTF.setFont(fuenteSans12P);
        receptorTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                receptorTFKeyReleased(evt);
            }
        });
        Panel.add(receptorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 30));

        jLabel4.setFont(fuenteSans12B);
        jLabel4.setForeground(new java.awt.Color(25, 30, 111));
        jLabel4.setText("*Receptor:");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        detalles.setFont(fuenteSans12P);
        Panel.add(detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 420, 90));

        Aceptar.setBackground(new java.awt.Color(120, 120, 120));
        Aceptar.setFont(fuenteSans12P);
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Aceptar.setContentAreaFilled(false);
        Aceptar.setEnabled(false);
        Aceptar.setOpaque(true);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        Panel.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 100, 40));

        Cancelar.setBackground(new java.awt.Color(25, 30, 111));
        Cancelar.setFont(fuenteSans12P);
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Cancelar.setContentAreaFilled(false);
        Cancelar.setOpaque(true);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        Panel.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        cantidadS=Integer.parseInt(cantidad.getText());
        String detal;
        String noNota = noNotaTF.getText();
        String receptor = receptorTF.getText();
        Date f = new Date();
        DateFormat DF = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fecha = DF.format(f);
        if(detalles.getText().compareToIgnoreCase("Opcional: Detalles de la salida del producto")!=0){
            detal = detalles.getText();
        }
        else{
            detal = "";
        }
        if(cantidadS>0){
            try {
                cantidadS=cantidadS*-1;
                float total = cantidadS*precioP;
                Statement stmt = con.createStatement();
                stmt.executeUpdate("INSERT INTO registro values(null,'"+fecha+"',"+cantidadS+","+total+",'"+detal+"','"+noNota+"','"+receptor+"','"+usuario+"','"+claveProducto+"')");
            } catch (SQLException ex) {
                Logger.getLogger(salidasProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        salida = true;
        this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        int c = evt.getKeyChar();
        if(!(c>47 && c<58)){
           evt.consume();
        }
    }//GEN-LAST:event_cantidadKeyTyped

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        if(cantidad.getText().length()>0){
            if(cantidad.getText().length()!=0){
                if(Integer.parseInt(cantidad.getText())>cantidadD){
                    cantidad.setText(cantidadD+"");
                }
            }
            String aux = cantidad.getText();
            if(aux!=null && aux.length()>0){
                int u = Integer.parseInt(aux);
                cantidad.setText(u+"");
                cantidad.setCaretPosition(cantidad.getText().length());
                String aux2 = noNotaTF.getText();
                String aux3 = receptorTF.getText();
                if(aux2.length()>0 && aux3.length()>0 && u>0){
                    Aceptar.setEnabled(true);
                    Aceptar.setBackground(azulF);
                }else{
                    Aceptar.setEnabled(false);
                    Aceptar.setBackground(gris);
                }
            }
        }else{
            if(!cantidad.isFocusOwner())
                cantidad.setText("0");
        }
    }//GEN-LAST:event_cantidadKeyReleased

    private void noNotaTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noNotaTFKeyReleased
        if(cantidad.getText().length()!=0){
            if(Integer.parseInt(cantidad.getText())>cantidadD){
                cantidad.setText(cantidadD+"");
            }
        }
        String aux = cantidad.getText();
        if(aux!=null && aux.length()>0){
            int u = Integer.parseInt(aux);
            String aux2 = noNotaTF.getText();
            String aux3 = receptorTF.getText();
            if(aux2.length()>0 && aux3.length()>0 && u>0){
                Aceptar.setEnabled(true);
                Aceptar.setBackground(azulF);
            }else{
                Aceptar.setEnabled(false);
                Aceptar.setBackground(gris);
            }
        }
    }//GEN-LAST:event_noNotaTFKeyReleased

    private void receptorTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receptorTFKeyReleased
        if(cantidad.getText().length()!=0){
            if(Integer.parseInt(cantidad.getText())>cantidadD){
                cantidad.setText(cantidadD+"");
            }
        }
        String aux = cantidad.getText();
        if(aux!=null && aux.length()>0){
            int u = Integer.parseInt(aux);
            String aux2 = noNotaTF.getText();
            String aux3 = receptorTF.getText();
            if(aux2.length()>0 && aux3.length()>0 && u>0){
                Aceptar.setEnabled(true);
                Aceptar.setBackground(azulF);
            }else{
                Aceptar.setEnabled(false);
                Aceptar.setBackground(gris);
            }
        }
    }//GEN-LAST:event_receptorTFKeyReleased

    private void cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadMouseClicked
        if(cantidad.getText().length()>0 && (cantidad.getSelectedText()==null || cantidad.getSelectedText().length()==0)){
            cantidad.selectAll();
        }
    }//GEN-LAST:event_cantidadMouseClicked

    public int getCantidadI() {
        return cantidadS;
    }

    public boolean isSalida() {
        return salida;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField detalles;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField noNotaTF;
    private javax.swing.JTextField receptorTF;
    // End of variables declaration//GEN-END:variables
}
